### PR TITLE
input: Fix thumbstick axis orientation

### LINKED ISSUE #21: GameController thumbstick Y axes are reversed
Testing against a PC build, the thumbstick Y axes are reversed (UP on PC is DOWN on Xbox and vice versa).

### PR DESCRIPTION
**Pull request by dracc**
Closes #21

Discussion around [here](https://discordapp.com/channels/428359196719972353/428360618102226946/666762102412804118) (discord).

Tested using the [NevolutionX/thumbstick](https://github.com/dracc/NevolutionX/tree/thumbstick) branch.

### CODE REVIEW

**Comment by sam-itt** [comment]
Tested using [Teo-ng/devel](https://github.com/sam-itt/teo-ng/tree/devel) branch, works as expected.

**Review by Ernegien — COMMENTED** [review]
I'd prefer to see the axis index represented as an enum. I don't quite understand the XOR and bit-shift copies but I also assume those to be SDL-specific data-munging; might be better to stick with regular integer operations to better convey meaning (or comment accordingly as to why this is required) and let the compiler do the optimizing...

**Comment by dracc** [comment]
Thanks for the review, @Ernegien!
The XOR is used in order to negate a signed 16bit value. Just using `operator-` gives bad values at the endpoints. I'll add a comment in the code. 👍

**Comment by Ernegien** [comment]
> Thanks for the review, @Ernegien!
> The XOR is used in order to negate an unsigned 16bit value. Just using `operator-` gives bad values at the endpoints. I'll add a comment in the code. 👍

In that case, if 65535 is technically the max value for an unsigned 16-bit value, "negating" that via your XOR operation gets you 0 as a value instead of -65535. Is there clamping going on elsewhere? Perhaps you're getting lucky with the XOR which does what you want it to but you don't fully understand why?

**Review by thrimbor — COMMENTED** [review]
The code looks fine (didn't get around to testing it yet), but I'd suggest to use the `~` operator instead, like SDL does for XInput: https://github.com/SDL-mirror/SDL/blob/8968393dbebacb4fe20eeb1d20276b5dbd26ebe8/src/joystick/windows/SDL_xinputjoystick.c#L440

I'd also suggest to add a small comment somewhere why this is done (possibly referencing SDL's XInput code which does the same).

**Comment by dracc** [comment]
I managed to push my branch before re-applying my changes... :see_no_evil:

**Comment by dracc** [comment]
Thank you @thrimbor for the review!
I've updated the code to reflect your comment, still works the same.
I also added a small comment describing what's going on.

File: src/joystick/xbox/SDL_xboxjoystick.c [hunk 1]
```diff
@@ -206,14 +206,20 @@ static void SDL_XBOX_JoystickUpdate(SDL_Joystick *joystick) {
 
     XPAD_INPUT *xpi = joystick->hwdata->padData;
 
+    /*
+     * Update the axes
+     * Thumbstick Y axes are negated as SDL and xpad values are mirrored.
+     * Same logic is used in XInput
+     * (../windows/SDL_xinputjoystick.c#440)
```
Comment (JayFoxRox) [inline src/joystick/xbox/SDL_xboxjoystick.c]: nit: Avoid mentioning line numbers or file-names; this reference will be invalid soon as line numbers change, and then this comment will be confusing instead of helpful. Just saying that it's the same as the XInput backend (or not saying anything at all where this comes from) is fine.

File: src/joystick/xbox/SDL_xboxjoystick.c [hunk 2]
```diff
@@ -206,14 +206,20 @@ static void SDL_XBOX_JoystickUpdate(SDL_Joystick *joystick) {
 
     XPAD_INPUT *xpi = joystick->hwdata->padData;
 
+    /*
+     * Update the axes
```
Comment (JayFoxRox) [inline src/joystick/xbox/SDL_xboxjoystick.c]: nit: "Update the axes**dot**"

File: src/joystick/xbox/SDL_xboxjoystick.c [hunk 3]
```diff
@@ -206,14 +206,20 @@ static void SDL_XBOX_JoystickUpdate(SDL_Joystick *joystick) {
...
+     * Thumbstick Y axes are negated as SDL and xpad values are mirrored.
```
Comment (JayFoxRox) [inline src/joystick/xbox/SDL_xboxjoystick.c]: nit: "mirrored" feels like the wrong word here? (I'd claim that mirrored can also mean "1:1 mapping" or "1 input = 2 outputs").
Not sure which one is most suitable, but "flipped", "reversed", "negated" or "inverted" are probably better.

To be honest, I feel with the new `~` syntax, the comment isn't necessary at all (I consider this less confusing than the trigger logic.. which also isn't described in a comment).

Comment (dracc) [reply src/joystick/xbox/SDL_xboxjoystick.c]: Comment removed. Thanks!
