### PR TITLE
build: Fix C++ header compatibility

### LINKED ISSUE #18: WIN32, _WIN32 and _MSC_VER  get undefined and cause errors
We undefine some variables in our SDL_platform.h:

https://github.com/XboxDev/nxdk-sdl/blob/4c6144a873f12f76b6cc20179d2d4000693b8133/include/SDL_platform.h#L68-L78

This causes problems. For example, C++ code that includes `<SDL.h>`:

```c++
#include <SDL.h>
int main() {}
```

Causes this error (and some others):

```
In file included from main.cpp:1:
In file included from <nxdk>/lib/sdl/SDL2/include/SDL.h:32:
In file included from <nxdk>/lib/sdl/SDL2/include/SDL_main.h:25:
In file included from <nxdk>/lib/sdl/SDL2/include/SDL_stdinc.h:37:
In file included from <nxdk>/lib/libcxx/include/stdio.h:101:
<nxdk>/lib/libcxx/include/__config:79:4: error: Unknown object file format
#  error Unknown object file format
```

### PR DESCRIPTION
**Pull request by thrimbor**
This attempts to solve the header compatibility issues caused by our SDL port's behavior of undefining `WIN32`, `_WIN32` and `_MSC_VER`.

One solution could've been to integrate the "are we building for Xbox" condition into all `#if` statements in the SDL codebase, but I feared that this might introduce countless merge conflicts when we update our fork in the future. So instead, these changes merely move the hack, so the preprocessor variables get only undefined when building SDL itself, and not in its public headers. It required some other minor changes, but it's still pretty small overall.

I tested this with a small C++ program to make sure the header conflict is gone now.

Fixes #18.

### CODE REVIEW

File: include/SDL_platform.h [hunk 1]
```diff
@@ -70,11 +70,12 @@
...
 #define __XBOX__ 1
-/* Don't assume we're building for Windows when targeting Xbox */
-#undef WIN32
-#undef _WIN32
-#undef _MSC_VER
-#define __GNUC__ 4
+/* clang doesn't like the SDL packing pragma headers */
+#pragma GCC diagnostic ignored "-Wpragma-pack"
+/* Disable SDL's weird feature of renaming main() */
+#define SDL_MAIN_HANDLED
```
Comment (JayFoxRox) [inline include/SDL_platform.h:76]: We should do this from the Makefile, so that (a later) CFLAGS can do `-USDL_MAIN_HANDLED` if the user actually wants this; note that I have not tested this

Comment (thrimbor) [reply include/SDL_platform.h:76]: If users really want it they can just use `#define main SDL_main` - I don't see why anybody would want it though, afaik it's only relevant when using `WinMain()`, which we don't have.

Comment (JayFoxRox) [reply include/SDL_platform.h:76]: Fair enough.

**Review by dracc — APPROVED** [review]
Tested by rebuilding NevolutionX, works.
Read through the code changes, look good to me.

**Comment by JayFoxRox** [comment]
Cool hack. Seems to work for me.

Merging.
